// This file is autogenerated. Changes will be overwritten.
#include "KM3OPOAUNE/moc_iaudiocontrol.cpp"
#include "KM3OPOAUNE/moc_iaudiosource.cpp"
#include "VU2PALRVTW/moc_alsink.cpp"
#include "VU2PALRVTW/moc_alsource.cpp"
#include "VU2PALRVTW/moc_openal.cpp"
