# CMake generated Testfile for 
# Source directory: /home/racha/qTox
# Build directory: /home/racha/qTox/build-integrated
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_core "/home/racha/qTox/build-integrated/test_core")
set_tests_properties(test_core PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;38;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_chatid "/home/racha/qTox/build-integrated/test_chatid")
set_tests_properties(test_chatid PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;39;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_toxid "/home/racha/qTox/build-integrated/test_toxid")
set_tests_properties(test_toxid PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;40;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_toxstring "/home/racha/qTox/build-integrated/test_toxstring")
set_tests_properties(test_toxstring PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;41;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_fileprogress "/home/racha/qTox/build-integrated/test_fileprogress")
set_tests_properties(test_fileprogress PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;42;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_textformatter "/home/racha/qTox/build-integrated/test_textformatter")
set_tests_properties(test_textformatter PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;43;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_bsu "/home/racha/qTox/build-integrated/test_bsu")
set_tests_properties(test_bsu PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;44;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_chatlinestorage "/home/racha/qTox/build-integrated/test_chatlinestorage")
set_tests_properties(test_chatlinestorage PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;45;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_paths "/home/racha/qTox/build-integrated/test_paths")
set_tests_properties(test_paths PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;46;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_dbschema "/home/racha/qTox/build-integrated/test_dbschema")
set_tests_properties(test_dbschema PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;47;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_dbTo11 "/home/racha/qTox/build-integrated/test_dbTo11")
set_tests_properties(test_dbTo11 PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;48;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_offlinemsgengine "/home/racha/qTox/build-integrated/test_offlinemsgengine")
set_tests_properties(test_offlinemsgengine PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;49;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_smileypack "/home/racha/qTox/build-integrated/test_smileypack")
set_tests_properties(test_smileypack PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;51;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_friendlistmanager "/home/racha/qTox/build-integrated/test_friendlistmanager")
set_tests_properties(test_friendlistmanager PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;53;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_friendmessagedispatcher "/home/racha/qTox/build-integrated/test_friendmessagedispatcher")
set_tests_properties(test_friendmessagedispatcher PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;54;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_conferencemessagedispatcher "/home/racha/qTox/build-integrated/test_conferencemessagedispatcher")
set_tests_properties(test_conferencemessagedispatcher PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;55;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_messageprocessor "/home/racha/qTox/build-integrated/test_messageprocessor")
set_tests_properties(test_messageprocessor PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;56;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_sessionchatlog "/home/racha/qTox/build-integrated/test_sessionchatlog")
set_tests_properties(test_sessionchatlog PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;57;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_exiftransform "/home/racha/qTox/build-integrated/test_exiftransform")
set_tests_properties(test_exiftransform PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;58;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_notificationgenerator "/home/racha/qTox/build-integrated/test_notificationgenerator")
set_tests_properties(test_notificationgenerator PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;59;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_filesform "/home/racha/qTox/build-integrated/test_filesform")
set_tests_properties(test_filesform PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;60;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_generalform "/home/racha/qTox/build-integrated/test_generalform")
set_tests_properties(test_generalform PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;61;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_identicon "/home/racha/qTox/build-integrated/test_identicon")
set_tests_properties(test_identicon PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;62;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_posixsignalnotifier "/home/racha/qTox/build-integrated/test_posixsignalnotifier")
set_tests_properties(test_posixsignalnotifier PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;73;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
add_test(test_stacktrace "/home/racha/qTox/build-integrated/test_stacktrace")
set_tests_properties(test_stacktrace PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/racha/qTox/cmake/Testing.cmake;25;add_test;/home/racha/qTox/cmake/Testing.cmake;74;auto_test;/home/racha/qTox/cmake/Testing.cmake;0;;/home/racha/qTox/CMakeLists.txt;677;include;/home/racha/qTox/CMakeLists.txt;0;")
subdirs("util")
subdirs("audio")
subdirs("translations")
subdirs("cmake/warnings")
subdirs("src/qml")
subdirs("test/mock")
subdirs("test/dbutility")
